site_name: Joaquin Gabriel Franco
theme:
  name: material
  font:
    text: Questrial
    code: Roboto Mono
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: red
      accent: deep orange
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: red
      accent: deep orange
  nav:
    - Home: index.md
    - Content: docs/content/
  features:
    - navigation.instant
    - search.highlight
    - content.code.annotate
  nav_style: primary
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - python
    - bash
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true # Enables tabbed code sections
plugins:
  - glightbox
  # - blog
extra_css:
  - styles/custom.css
copyright: Copyright &copy; 2025 Joaquin Franco
