site_name: Joaquin Gabriel Franco
theme:
  name: material
  font:
    text: Questrial
    code: Roboto Mono
  icon:
    logo: octicons/feed-person-16
  palette:
    # # Dark Mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to light mode
    #   primary: custom
    #   accent: red
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      # toggle:
      #   icon: material/toggle-switch
      #   name: Switch to dark mode
      primary: custom
      accent: red
  nav:
    - Home: index.md
    - Portfolio: docs/portfolio/
    - Content: docs/content/
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.suggest
  nav_style: primary
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - python
    - bash
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.emoji
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true # Enables tabbed code sections
plugins:
  - glightbox
  # - blog
extra_css:
  - styles/custom.css
copyright: Copyright &copy; 2025 Joaquin Franco
